// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ParamServer {
class Command;
class CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
class GradientRequest;
class GradientRequestDefaultTypeInternal;
extern GradientRequestDefaultTypeInternal _GradientRequest_default_instance_;
class GradientRequest_GradientMapEntry;
class GradientRequest_GradientMapEntryDefaultTypeInternal;
extern GradientRequest_GradientMapEntryDefaultTypeInternal _GradientRequest_GradientMapEntry_default_instance_;
class ParamRequest;
class ParamRequestDefaultTypeInternal;
extern ParamRequestDefaultTypeInternal _ParamRequest_default_instance_;
class ParamResponse;
class ParamResponseDefaultTypeInternal;
extern ParamResponseDefaultTypeInternal _ParamResponse_default_instance_;
class ParamResponse_ParamMapEntry;
class ParamResponse_ParamMapEntryDefaultTypeInternal;
extern ParamResponse_ParamMapEntryDefaultTypeInternal _ParamResponse_ParamMapEntry_default_instance_;
}  // namespace ParamServer

namespace ParamServer {

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_message_2eproto

enum Command_Type {
  Command_Type_TRAINING_COMPLETE = 0,
  Command_Type_START_TEST = 1,
  Command_Type_TEST_COMPLETE = 2,
  Command_Type_SHUTDOWN = 3
};
bool Command_Type_IsValid(int value);
const Command_Type Command_Type_Type_MIN = Command_Type_TRAINING_COMPLETE;
const Command_Type Command_Type_Type_MAX = Command_Type_SHUTDOWN;
const int Command_Type_Type_ARRAYSIZE = Command_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Command_Type_descriptor();
inline const ::std::string& Command_Type_Name(Command_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Command_Type_descriptor(), value);
}
inline bool Command_Type_Parse(
    const ::std::string& name, Command_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Command_Type>(
    Command_Type_descriptor(), name, value);
}
// ===================================================================

class ParamRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ParamServer.ParamRequest) */ {
 public:
  ParamRequest();
  virtual ~ParamRequest();

  ParamRequest(const ParamRequest& from);

  inline ParamRequest& operator=(const ParamRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParamRequest& default_instance();

  static inline const ParamRequest* internal_default_instance() {
    return reinterpret_cast<const ParamRequest*>(
               &_ParamRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ParamRequest* other);

  // implements Message ----------------------------------------------

  inline ParamRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ParamRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ParamRequest& from);
  void MergeFrom(const ParamRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ParamRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 feature_id = 1;
  int feature_id_size() const;
  void clear_feature_id();
  static const int kFeatureIdFieldNumber = 1;
  ::google::protobuf::int32 feature_id(int index) const;
  void set_feature_id(int index, ::google::protobuf::int32 value);
  void add_feature_id(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      feature_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_feature_id();

  // @@protoc_insertion_point(class_scope:ParamServer.ParamRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > feature_id_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class ParamResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ParamServer.ParamResponse) */ {
 public:
  ParamResponse();
  virtual ~ParamResponse();

  ParamResponse(const ParamResponse& from);

  inline ParamResponse& operator=(const ParamResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParamResponse& default_instance();

  static inline const ParamResponse* internal_default_instance() {
    return reinterpret_cast<const ParamResponse*>(
               &_ParamResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ParamResponse* other);

  // implements Message ----------------------------------------------

  inline ParamResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ParamResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ParamResponse& from);
  void MergeFrom(const ParamResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ParamResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, float> param_map = 1;
  int param_map_size() const;
  void clear_param_map();
  static const int kParamMapFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, float >&
      param_map() const;
  ::google::protobuf::Map< ::google::protobuf::int32, float >*
      mutable_param_map();

  // @@protoc_insertion_point(class_scope:ParamServer.ParamResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  public:
  class ParamResponse_ParamMapEntry : public ::google::protobuf::internal::MapEntry<ParamResponse_ParamMapEntry, 
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<ParamResponse_ParamMapEntry, 
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > SuperType;
    ParamResponse_ParamMapEntry();
    ParamResponse_ParamMapEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const ParamResponse_ParamMapEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_ParamResponse_ParamMapEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      ParamResponse_ParamMapEntry,
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > param_map_;
  private:
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class GradientRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ParamServer.GradientRequest) */ {
 public:
  GradientRequest();
  virtual ~GradientRequest();

  GradientRequest(const GradientRequest& from);

  inline GradientRequest& operator=(const GradientRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GradientRequest& default_instance();

  static inline const GradientRequest* internal_default_instance() {
    return reinterpret_cast<const GradientRequest*>(
               &_GradientRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(GradientRequest* other);

  // implements Message ----------------------------------------------

  inline GradientRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GradientRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GradientRequest& from);
  void MergeFrom(const GradientRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GradientRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, float> gradient_map = 1;
  int gradient_map_size() const;
  void clear_gradient_map();
  static const int kGradientMapFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, float >&
      gradient_map() const;
  ::google::protobuf::Map< ::google::protobuf::int32, float >*
      mutable_gradient_map();

  // @@protoc_insertion_point(class_scope:ParamServer.GradientRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  public:
  class GradientRequest_GradientMapEntry : public ::google::protobuf::internal::MapEntry<GradientRequest_GradientMapEntry, 
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<GradientRequest_GradientMapEntry, 
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > SuperType;
    GradientRequest_GradientMapEntry();
    GradientRequest_GradientMapEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const GradientRequest_GradientMapEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_GradientRequest_GradientMapEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      GradientRequest_GradientMapEntry,
      ::google::protobuf::int32, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > gradient_map_;
  private:
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ParamServer.Command) */ {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Command& default_instance();

  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Command* other);

  // implements Message ----------------------------------------------

  inline Command* New() const PROTOBUF_FINAL { return New(NULL); }

  Command* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Command_Type Type;
  static const Type TRAINING_COMPLETE =
    Command_Type_TRAINING_COMPLETE;
  static const Type START_TEST =
    Command_Type_START_TEST;
  static const Type TEST_COMPLETE =
    Command_Type_TEST_COMPLETE;
  static const Type SHUTDOWN =
    Command_Type_SHUTDOWN;
  static inline bool Type_IsValid(int value) {
    return Command_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Command_Type_Type_MIN;
  static const Type Type_MAX =
    Command_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Command_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Command_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Command_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Command_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .ParamServer.Command.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::ParamServer::Command_Type type() const;
  void set_type(::ParamServer::Command_Type value);

  // @@protoc_insertion_point(class_scope:ParamServer.Command)
 private:
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int type_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ParamRequest

// repeated int32 feature_id = 1;
inline int ParamRequest::feature_id_size() const {
  return feature_id_.size();
}
inline void ParamRequest::clear_feature_id() {
  feature_id_.Clear();
}
inline ::google::protobuf::int32 ParamRequest::feature_id(int index) const {
  // @@protoc_insertion_point(field_get:ParamServer.ParamRequest.feature_id)
  return feature_id_.Get(index);
}
inline void ParamRequest::set_feature_id(int index, ::google::protobuf::int32 value) {
  feature_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParamServer.ParamRequest.feature_id)
}
inline void ParamRequest::add_feature_id(::google::protobuf::int32 value) {
  feature_id_.Add(value);
  // @@protoc_insertion_point(field_add:ParamServer.ParamRequest.feature_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ParamRequest::feature_id() const {
  // @@protoc_insertion_point(field_list:ParamServer.ParamRequest.feature_id)
  return feature_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ParamRequest::mutable_feature_id() {
  // @@protoc_insertion_point(field_mutable_list:ParamServer.ParamRequest.feature_id)
  return &feature_id_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ParamResponse

// map<int32, float> param_map = 1;
inline int ParamResponse::param_map_size() const {
  return param_map_.size();
}
inline void ParamResponse::clear_param_map() {
  param_map_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, float >&
ParamResponse::param_map() const {
  // @@protoc_insertion_point(field_map:ParamServer.ParamResponse.param_map)
  return param_map_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, float >*
ParamResponse::mutable_param_map() {
  // @@protoc_insertion_point(field_mutable_map:ParamServer.ParamResponse.param_map)
  return param_map_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GradientRequest

// map<int32, float> gradient_map = 1;
inline int GradientRequest::gradient_map_size() const {
  return gradient_map_.size();
}
inline void GradientRequest::clear_gradient_map() {
  gradient_map_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, float >&
GradientRequest::gradient_map() const {
  // @@protoc_insertion_point(field_map:ParamServer.GradientRequest.gradient_map)
  return gradient_map_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, float >*
GradientRequest::mutable_gradient_map() {
  // @@protoc_insertion_point(field_mutable_map:ParamServer.GradientRequest.gradient_map)
  return gradient_map_.MutableMap();
}

// -------------------------------------------------------------------

// Command

// optional .ParamServer.Command.Type type = 1;
inline bool Command::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Command::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Command::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Command::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::ParamServer::Command_Type Command::type() const {
  // @@protoc_insertion_point(field_get:ParamServer.Command.type)
  return static_cast< ::ParamServer::Command_Type >(type_);
}
inline void Command::set_type(::ParamServer::Command_Type value) {
  assert(::ParamServer::Command_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:ParamServer.Command.type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace ParamServer

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ParamServer::Command_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ParamServer::Command_Type>() {
  return ::ParamServer::Command_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
