// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ParamServer {
class ParamRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ParamRequest> {
} _ParamRequest_default_instance_;
class ParamResponse_ParamMapEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ParamResponse::ParamResponse_ParamMapEntry> {
} _ParamResponse_ParamMapEntry_default_instance_;
class ParamResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ParamResponse> {
} _ParamResponse_default_instance_;
class GradientRequest_GradientMapEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<GradientRequest::GradientRequest_GradientMapEntry> {
} _GradientRequest_GradientMapEntry_default_instance_;
class GradientRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<GradientRequest> {
} _GradientRequest_default_instance_;
class CommandDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Command> {
} _Command_default_instance_;

namespace protobuf_message_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamRequest, feature_id_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamResponse, param_map_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientRequest, gradient_map_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, type_),
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(ParamRequest)},
  { 7, 13, sizeof(ParamResponse)},
  { 14, 20, sizeof(GradientRequest)},
  { 21, 27, sizeof(Command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ParamRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ParamResponse_ParamMapEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ParamResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_GradientRequest_GradientMapEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_GradientRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Command_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
file_level_metadata[1].reflection = ParamResponse::ParamResponse_ParamMapEntry::CreateReflection(file_level_metadata[1].descriptor, _ParamResponse_ParamMapEntry_default_instance_.get_mutable());
file_level_metadata[3].reflection = GradientRequest::GradientRequest_GradientMapEntry::CreateReflection(file_level_metadata[3].descriptor, _GradientRequest_GradientMapEntry_default_instance_.get_mutable());
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

}  // namespace

void TableStruct::Shutdown() {
  _ParamRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _ParamResponse_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _GradientRequest_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
  _Command_default_instance_.Shutdown();
  delete file_level_metadata[5].reflection;
  delete file_level_metadata[1].reflection;
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ParamRequest_default_instance_.DefaultConstruct();
  _ParamResponse_ParamMapEntry_default_instance_.DefaultConstruct();
  _ParamResponse_default_instance_.DefaultConstruct();
  _GradientRequest_GradientMapEntry_default_instance_.DefaultConstruct();
  _GradientRequest_default_instance_.DefaultConstruct();
  _Command_default_instance_.DefaultConstruct();
  _ParamResponse_ParamMapEntry_default_instance_.get_mutable()->set_default_instance(_ParamResponse_ParamMapEntry_default_instance_.get_mutable());
  _ParamResponse_ParamMapEntry_default_instance_.get_mutable()->InitAsDefaultInstance();
  _GradientRequest_GradientMapEntry_default_instance_.get_mutable()->set_default_instance(_GradientRequest_GradientMapEntry_default_instance_.get_mutable());
  _GradientRequest_GradientMapEntry_default_instance_.get_mutable()->InitAsDefaultInstance();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rmessage.proto\022\013ParamServer\"\"\n\014ParamReq"
      "uest\022\022\n\nfeature_id\030\001 \003(\005\"}\n\rParamRespons"
      "e\022;\n\tparam_map\030\001 \003(\0132(.ParamServer.Param"
      "Response.ParamMapEntry\032/\n\rParamMapEntry\022"
      "\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\002:\0028\001\"\212\001\n\017Grad"
      "ientRequest\022C\n\014gradient_map\030\001 \003(\0132-.Para"
      "mServer.GradientRequest.GradientMapEntry"
      "\0322\n\020GradientMapEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005val"
      "ue\030\002 \001(\002:\0028\001\"\202\001\n\007Command\022\'\n\004type\030\001 \001(\0162\031"
      ".ParamServer.Command.Type\"N\n\004Type\022\025\n\021TRA"
      "INING_COMPLETE\020\000\022\016\n\nSTART_TEST\020\001\022\021\n\rTEST"
      "_COMPLETE\020\002\022\014\n\010SHUTDOWN\020\003"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 465);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_message_2eproto

const ::google::protobuf::EnumDescriptor* Command_Type_descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[0];
}
bool Command_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Command_Type Command::TRAINING_COMPLETE;
const Command_Type Command::START_TEST;
const Command_Type Command::TEST_COMPLETE;
const Command_Type Command::SHUTDOWN;
const Command_Type Command::Type_MIN;
const Command_Type Command::Type_MAX;
const int Command::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParamRequest::kFeatureIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParamRequest::ParamRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ParamServer.ParamRequest)
}
ParamRequest::ParamRequest(const ParamRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      feature_id_(from.feature_id_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ParamServer.ParamRequest)
}

void ParamRequest::SharedCtor() {
  _cached_size_ = 0;
}

ParamRequest::~ParamRequest() {
  // @@protoc_insertion_point(destructor:ParamServer.ParamRequest)
  SharedDtor();
}

void ParamRequest::SharedDtor() {
}

void ParamRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParamRequest::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParamRequest& ParamRequest::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

ParamRequest* ParamRequest::New(::google::protobuf::Arena* arena) const {
  ParamRequest* n = new ParamRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParamRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamServer.ParamRequest)
  feature_id_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParamRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ParamServer.ParamRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 feature_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8u, input, this->mutable_feature_id())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_feature_id())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ParamServer.ParamRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ParamServer.ParamRequest)
  return false;
#undef DO_
}

void ParamRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ParamServer.ParamRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 feature_id = 1;
  for (int i = 0, n = this->feature_id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->feature_id(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ParamServer.ParamRequest)
}

::google::protobuf::uint8* ParamRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamServer.ParamRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 feature_id = 1;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(1, this->feature_id_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamServer.ParamRequest)
  return target;
}

size_t ParamRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamServer.ParamRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated int32 feature_id = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->feature_id_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->feature_id_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParamRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ParamServer.ParamRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ParamRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParamRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ParamServer.ParamRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ParamServer.ParamRequest)
    MergeFrom(*source);
  }
}

void ParamRequest::MergeFrom(const ParamRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ParamServer.ParamRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  feature_id_.MergeFrom(from.feature_id_);
}

void ParamRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ParamServer.ParamRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParamRequest::CopyFrom(const ParamRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamServer.ParamRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamRequest::IsInitialized() const {
  return true;
}

void ParamRequest::Swap(ParamRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParamRequest::InternalSwap(ParamRequest* other) {
  feature_id_.InternalSwap(&other->feature_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParamRequest::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParamRequest

// repeated int32 feature_id = 1;
int ParamRequest::feature_id_size() const {
  return feature_id_.size();
}
void ParamRequest::clear_feature_id() {
  feature_id_.Clear();
}
::google::protobuf::int32 ParamRequest::feature_id(int index) const {
  // @@protoc_insertion_point(field_get:ParamServer.ParamRequest.feature_id)
  return feature_id_.Get(index);
}
void ParamRequest::set_feature_id(int index, ::google::protobuf::int32 value) {
  feature_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:ParamServer.ParamRequest.feature_id)
}
void ParamRequest::add_feature_id(::google::protobuf::int32 value) {
  feature_id_.Add(value);
  // @@protoc_insertion_point(field_add:ParamServer.ParamRequest.feature_id)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ParamRequest::feature_id() const {
  // @@protoc_insertion_point(field_list:ParamServer.ParamRequest.feature_id)
  return feature_id_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ParamRequest::mutable_feature_id() {
  // @@protoc_insertion_point(field_mutable_list:ParamServer.ParamRequest.feature_id)
  return &feature_id_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

ParamResponse::ParamResponse_ParamMapEntry::ParamResponse_ParamMapEntry() {}
ParamResponse::ParamResponse_ParamMapEntry::ParamResponse_ParamMapEntry(::google::protobuf::Arena* arena) : SuperType(arena) {}
::google::protobuf::Metadata ParamResponse::ParamResponse_ParamMapEntry::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[1];
}
void ParamResponse::ParamResponse_ParamMapEntry::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}
void ParamResponse::ParamResponse_ParamMapEntry::MergeFrom(const ParamResponse_ParamMapEntry& other) {
  MergeFromInternal(other);
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParamResponse::kParamMapFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParamResponse::ParamResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ParamServer.ParamResponse)
}
ParamResponse::ParamResponse(const ParamResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  param_map_.MergeFrom(from.param_map_);
  // @@protoc_insertion_point(copy_constructor:ParamServer.ParamResponse)
}

void ParamResponse::SharedCtor() {
  _cached_size_ = 0;
}

ParamResponse::~ParamResponse() {
  // @@protoc_insertion_point(destructor:ParamServer.ParamResponse)
  SharedDtor();
}

void ParamResponse::SharedDtor() {
}

void ParamResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParamResponse::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParamResponse& ParamResponse::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

ParamResponse* ParamResponse::New(::google::protobuf::Arena* arena) const {
  ParamResponse* n = new ParamResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParamResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamServer.ParamResponse)
  param_map_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParamResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ParamServer.ParamResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<int32, float> param_map = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          ParamResponse_ParamMapEntry::Parser< ::google::protobuf::internal::MapField<
              ParamResponse_ParamMapEntry,
              ::google::protobuf::int32, float,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, float > > parser(&param_map_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ParamServer.ParamResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ParamServer.ParamResponse)
  return false;
#undef DO_
}

void ParamResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ParamServer.ParamResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, float> param_map = 1;
  if (!this->param_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->param_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->param_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->param_map().begin();
          it != this->param_map().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<ParamResponse_ParamMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(param_map_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<ParamResponse_ParamMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->param_map().begin();
          it != this->param_map().end(); ++it) {
        entry.reset(param_map_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ParamServer.ParamResponse)
}

::google::protobuf::uint8* ParamResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamServer.ParamResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, float> param_map = 1;
  if (!this->param_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->param_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->param_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->param_map().begin();
          it != this->param_map().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<ParamResponse_ParamMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(param_map_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<ParamResponse_ParamMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->param_map().begin();
          it != this->param_map().end(); ++it) {
        entry.reset(param_map_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamServer.ParamResponse)
  return target;
}

size_t ParamResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamServer.ParamResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // map<int32, float> param_map = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->param_map_size());
  {
    ::google::protobuf::scoped_ptr<ParamResponse_ParamMapEntry> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
        it = this->param_map().begin();
        it != this->param_map().end(); ++it) {
      entry.reset(param_map_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParamResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ParamServer.ParamResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ParamResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParamResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ParamServer.ParamResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ParamServer.ParamResponse)
    MergeFrom(*source);
  }
}

void ParamResponse::MergeFrom(const ParamResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ParamServer.ParamResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  param_map_.MergeFrom(from.param_map_);
}

void ParamResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ParamServer.ParamResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParamResponse::CopyFrom(const ParamResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamServer.ParamResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamResponse::IsInitialized() const {
  return true;
}

void ParamResponse::Swap(ParamResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParamResponse::InternalSwap(ParamResponse* other) {
  param_map_.Swap(&other->param_map_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParamResponse::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParamResponse

// map<int32, float> param_map = 1;
int ParamResponse::param_map_size() const {
  return param_map_.size();
}
void ParamResponse::clear_param_map() {
  param_map_.Clear();
}
 const ::google::protobuf::Map< ::google::protobuf::int32, float >&
ParamResponse::param_map() const {
  // @@protoc_insertion_point(field_map:ParamServer.ParamResponse.param_map)
  return param_map_.GetMap();
}
 ::google::protobuf::Map< ::google::protobuf::int32, float >*
ParamResponse::mutable_param_map() {
  // @@protoc_insertion_point(field_mutable_map:ParamServer.ParamResponse.param_map)
  return param_map_.MutableMap();
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

GradientRequest::GradientRequest_GradientMapEntry::GradientRequest_GradientMapEntry() {}
GradientRequest::GradientRequest_GradientMapEntry::GradientRequest_GradientMapEntry(::google::protobuf::Arena* arena) : SuperType(arena) {}
::google::protobuf::Metadata GradientRequest::GradientRequest_GradientMapEntry::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[3];
}
void GradientRequest::GradientRequest_GradientMapEntry::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}
void GradientRequest::GradientRequest_GradientMapEntry::MergeFrom(const GradientRequest_GradientMapEntry& other) {
  MergeFromInternal(other);
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GradientRequest::kGradientMapFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GradientRequest::GradientRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ParamServer.GradientRequest)
}
GradientRequest::GradientRequest(const GradientRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  gradient_map_.MergeFrom(from.gradient_map_);
  // @@protoc_insertion_point(copy_constructor:ParamServer.GradientRequest)
}

void GradientRequest::SharedCtor() {
  _cached_size_ = 0;
}

GradientRequest::~GradientRequest() {
  // @@protoc_insertion_point(destructor:ParamServer.GradientRequest)
  SharedDtor();
}

void GradientRequest::SharedDtor() {
}

void GradientRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GradientRequest::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GradientRequest& GradientRequest::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

GradientRequest* GradientRequest::New(::google::protobuf::Arena* arena) const {
  GradientRequest* n = new GradientRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GradientRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamServer.GradientRequest)
  gradient_map_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool GradientRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ParamServer.GradientRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<int32, float> gradient_map = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          GradientRequest_GradientMapEntry::Parser< ::google::protobuf::internal::MapField<
              GradientRequest_GradientMapEntry,
              ::google::protobuf::int32, float,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, float > > parser(&gradient_map_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ParamServer.GradientRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ParamServer.GradientRequest)
  return false;
#undef DO_
}

void GradientRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ParamServer.GradientRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, float> gradient_map = 1;
  if (!this->gradient_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->gradient_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->gradient_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->gradient_map().begin();
          it != this->gradient_map().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<GradientRequest_GradientMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(gradient_map_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<GradientRequest_GradientMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->gradient_map().begin();
          it != this->gradient_map().end(); ++it) {
        entry.reset(gradient_map_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ParamServer.GradientRequest)
}

::google::protobuf::uint8* GradientRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamServer.GradientRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, float> gradient_map = 1;
  if (!this->gradient_map().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->gradient_map().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->gradient_map().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->gradient_map().begin();
          it != this->gradient_map().end(); ++it, ++n) {
        items[n] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[n], Less());
      ::google::protobuf::scoped_ptr<GradientRequest_GradientMapEntry> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(gradient_map_.NewEntryWrapper(
            items[i].second->first, items[i].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<GradientRequest_GradientMapEntry> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
          it = this->gradient_map().begin();
          it != this->gradient_map().end(); ++it) {
        entry.reset(gradient_map_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamServer.GradientRequest)
  return target;
}

size_t GradientRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamServer.GradientRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // map<int32, float> gradient_map = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->gradient_map_size());
  {
    ::google::protobuf::scoped_ptr<GradientRequest_GradientMapEntry> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, float >::const_iterator
        it = this->gradient_map().begin();
        it != this->gradient_map().end(); ++it) {
      entry.reset(gradient_map_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GradientRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ParamServer.GradientRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GradientRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GradientRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ParamServer.GradientRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ParamServer.GradientRequest)
    MergeFrom(*source);
  }
}

void GradientRequest::MergeFrom(const GradientRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ParamServer.GradientRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  gradient_map_.MergeFrom(from.gradient_map_);
}

void GradientRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ParamServer.GradientRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GradientRequest::CopyFrom(const GradientRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamServer.GradientRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GradientRequest::IsInitialized() const {
  return true;
}

void GradientRequest::Swap(GradientRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GradientRequest::InternalSwap(GradientRequest* other) {
  gradient_map_.Swap(&other->gradient_map_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GradientRequest::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GradientRequest

// map<int32, float> gradient_map = 1;
int GradientRequest::gradient_map_size() const {
  return gradient_map_.size();
}
void GradientRequest::clear_gradient_map() {
  gradient_map_.Clear();
}
 const ::google::protobuf::Map< ::google::protobuf::int32, float >&
GradientRequest::gradient_map() const {
  // @@protoc_insertion_point(field_map:ParamServer.GradientRequest.gradient_map)
  return gradient_map_.GetMap();
}
 ::google::protobuf::Map< ::google::protobuf::int32, float >*
GradientRequest::mutable_gradient_map() {
  // @@protoc_insertion_point(field_mutable_map:ParamServer.GradientRequest.gradient_map)
  return gradient_map_.MutableMap();
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Command::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Command::Command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ParamServer.Command)
}
Command::Command(const Command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:ParamServer.Command)
}

void Command::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
}

Command::~Command() {
  // @@protoc_insertion_point(destructor:ParamServer.Command)
  SharedDtor();
}

void Command::SharedDtor() {
}

void Command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Command::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Command& Command::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Command* Command::New(::google::protobuf::Arena* arena) const {
  Command* n = new Command;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Command::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamServer.Command)
  type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ParamServer.Command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ParamServer.Command.Type type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ParamServer::Command_Type_IsValid(value)) {
            set_type(static_cast< ::ParamServer::Command_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ParamServer.Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ParamServer.Command)
  return false;
#undef DO_
}

void Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ParamServer.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .ParamServer.Command.Type type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ParamServer.Command)
}

::google::protobuf::uint8* Command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamServer.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .ParamServer.Command.Type type = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamServer.Command)
  return target;
}

size_t Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamServer.Command)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional .ParamServer.Command.Type type = 1;
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ParamServer.Command)
  GOOGLE_DCHECK_NE(&from, this);
  const Command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ParamServer.Command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ParamServer.Command)
    MergeFrom(*source);
  }
}

void Command::MergeFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ParamServer.Command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_type()) {
    set_type(from.type());
  }
}

void Command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ParamServer.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command::CopyFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamServer.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command::IsInitialized() const {
  return true;
}

void Command::Swap(Command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Command::InternalSwap(Command* other) {
  std::swap(type_, other->type_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Command::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Command

// optional .ParamServer.Command.Type type = 1;
bool Command::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Command::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
void Command::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void Command::clear_type() {
  type_ = 0;
  clear_has_type();
}
::ParamServer::Command_Type Command::type() const {
  // @@protoc_insertion_point(field_get:ParamServer.Command.type)
  return static_cast< ::ParamServer::Command_Type >(type_);
}
void Command::set_type(::ParamServer::Command_Type value) {
  assert(::ParamServer::Command_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:ParamServer.Command.type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ParamServer

// @@protoc_insertion_point(global_scope)
